FROM ubuntu:16.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip python3-dev python3-setuptools \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* \
    && pip3 install tensorflow==1.4.1
